name: people-dev

networks:
  backend:
    driver: bridge

services:
  db:
    image: postgres:18-alpine3.22
    restart: always
    user: postgres
    
    secrets:
      - db-password
      - keycloak-db-password
      - api-db-password
    
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro  # Initialization scripts
    
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    ports:
      - "5432:5432"
    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    
    command: start-dev

    # Run import
    # command: start-dev --import-realm  # Add --import-realm flag to import on startup
    
    volumes:
      - ./keycloak/export:/opt/keycloak/data/import

    depends_on:
      db:
        condition: service_healthy
    
    ports:
      - "8080:8080"
      - "9000:9000"  # Admin health endpoint
    
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_HOSTNAME: keycloak
      KC_HOSTNAME: localhost # If Keycloak is accessed only locally
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/keycloak/9000 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: keycloak\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s  # Keycloak takes time to initialize
    
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    
    working_dir: /app
    
    #command: .mvnw -q spring-boot:run
    
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    
    environment:
      MAVEN_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/people
      SPRING_DATASOURCE_USERNAME: people
      SPRING_DATASOURCE_PASSWORD: people
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/people-realm

    ports:
      - "8081:8081"
      - "5005:5005"
    
    volumes:
#      - ./:/app
      - ~/.m2:/root/.m2
    
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
    
    tty: true
    
    networks:
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: ./secrets/db-password.txt
  api-db-password:
    file: ./secrets/api-db-password.txt
  keycloak-db-password:
    file: ./secrets/keycloak-db-password.txt