# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  app:
    container_name: app
    image: mcqueide/people-api:ci
    build:
      context: .
      dockerfile: Dockerfile
      target: ci

    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/people
      - SPRING_DATASOURCE_USERNAME=people
      - SPRING_DATASOURCE_PASSWORD=people
      - JAVA_OPTS="-XX:+UseG1GC -XX:MaxRAMPercentage=75"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18-alpine3.22
    container_name: db
    
    user: postgres
    environment:
      - POSTGRES_DB=people
      - POSTGRES_USER=people
      - POSTGRES_PASSWORD=people
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -U people" ]
      interval: 10s
      timeout: 5s
      retries: 5